import { ReactNode } from 'react';
import { Inter } from 'next/font/google';

import Layout from '@/styling/layout';
import '../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App Test',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="kor">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
